### ISSUE TITLE
incorrect cell volumes total for step 0

### ISSUE THREAD

**Issue by rheiland** [MathCancer/PhysiCell#22] opened 2019-06-26 09:49 UTC
(reported by a user)
The total cells volume that is stored in the matlab files in Output00000000.xml is shown as 1. This appears to be correct for all subsequent steps.

e.g. when running the base 2D model (same is true in 3D)

MATLAB code
MCDS = read_MultiCellDS_xml( 'output00000000.xml'); 
MCDS.discrete_cells.phenotype.geometrical_properties.volumes
MCDS.discrete_cells.phenotype.geometrical_properties.volumes.total_volume

MCDS = read_MultiCellDS_xml( 'output00000001.xml'); 
MCDS.discrete_cells.phenotype.geometrical_properties.volumes
MCDS.discrete_cells.phenotype.geometrical_properties.volumes.total_volume

gives

output00000000_cells_physicell.mat
Elapsed time is 0.347925 seconds.

Summary for file ./output00000000.xml:
Voxels: 2500
Substrates: 1
  oxygen (mmHg)
Cells: 4
ans = struct with fields:
          total_volume: [4×1 double]
               nuclear: [540 540 540 540]
           cytoplasmic: [1954 1954 1954 1954]
        fluid_fraction: [0.7500 0.7500 0.7500 0.7500]
    calcified_fraction: [0 0 0 0]
ans = 4×1
     1
     1
     1
     1
output00000001_cells_physicell.mat
Elapsed time is 0.325475 seconds.

Summary for file ./output00000001.xml:
Voxels: 2500
Substrates: 1
  oxygen (mmHg)
Cells: 4
ans = struct with fields:
          total_volume: [4×1 double]
               nuclear: [540 844.3312 791.9927 540]
           cytoplasmic: [1954 2.9191e+03 2.7346e+03 1954]
        fluid_fraction: [0.7500 0.7500 0.7500 0.7500]
    calcified_fraction: [0 0 0 0]
ans = 4×1
103 ×
    2.4940
    3.7634
    3.5266
    2.4940

where ans=total volume

**Comment by MathCancer** [comment] 2020-02-27 04:50
OK, I can confirm that the default constructor for the Volume class is indeed initializing to non-one, so this bug is purely in the output and not in the actual simulation.

**Comment by MathCancer** [comment] 2020-02-27 05:18
OK, so Cell::Cell needs to call 	set_total_volume( phenotype.volume.total ) so that BioFVM knows the total volume. BioFVM saves basic cell information (including volumes) that are read by all our read routines. Since the BioFVM information had not yet been updated, the BioFVM defaults of 1 cubic micron are written to the initial data. 

Before the fix, this gets called after the first volume update, explaining why the volumes were fine at the next save time. 

Now, Cell::Cell() and the create_cells() functions properly call this functoin so that all cells get teh right volume at their time of creation. 

This issue is now fixed. Thank you for the bug report!

In the future, please note that the preferred support tracker is at SourceForge: 

https://sourceforge.net/p/physicell/tickets/

**Closed by MathCancer** 2020-02-27 05:18 UTC
